language: elixir
elixir:
  - 1.3.4
env:
  - MIX_ENV=test

script:
  - mix deps.get --only test
  - mix compile
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
